// /app/api/fake-market-data/route.js

const fakeData = [
        {
          state: 'Maharashtra',
          district: 'Nagpur',
          market: 'Nagpur',
          commodity: 'Cotton',
          variety: 'American Cotton',
          grade: 'A',
          min_price: 5100,
          max_price: 5700,
          modal_price: 5400,
          date: '2025-04-10',
        },
        {
          state: 'Maharashtra',
          district: 'Nagpur',
          market: 'Nagpur',
          commodity: 'Cotton',
          variety: 'American Cotton',
          grade: 'A',
          min_price: 5200,
          max_price: 5800,
          modal_price: 5500,
          date: '2025-04-11',
        },
        {
          state: 'Maharashtra',
          district: 'Nagpur',
          market: 'Nagpur',
          commodity: 'Cotton',
          variety: 'American Cotton',
          grade: 'A',
          min_price: 5000,
          max_price: 5600,
          modal_price: 5300,
          date: '2025-04-11',
        },
        {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 7000,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 1000,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 5000,
            max_price: 5600,
            modal_price: 5300,
            date: '2025-04-11',
          },
          {
            state: 'Maharashtra',
            district: 'Nagpur',
            market: 'Nagpur',
            commodity: 'Cotton',
            variety: 'American Cotton',
            grade: 'A',
            min_price: 1000,
            max_price: 5600,
            modal_price: 1000,
            date: '2024-04-11',
          },
        // ...other entries      
  ];
  
  export async function POST(request) {
    const { state, district, commodity } = await request.json();
  
    const result = fakeData.filter(
      (item) =>
        item.state.toLowerCase() === state.toLowerCase() &&
        item.district.toLowerCase() === district.toLowerCase() &&
        item.commodity.toLowerCase() === commodity.toLowerCase()
    );
  
    return Response.json(result);
  }
  